[tool.poetry]
name = "aula-17"
version = "0.1.0"
description = ""
authors = ["Roberto Melo Jr <robertomelojr@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"
sqlalchemy = "^2.0.37"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
